Rely on VDAF's definitions of privacy, robustness
ietf-wg-ppm/draft-ietf-ppm-dap pull request #309
Opened 2022-08-29 20:05 UTC by tgeoghegan

Resolves #306

2022-08-29 20:53 UTC, divergentdave approved these changes

2022-08-29 20:56 UTC, branlwyd approved these changes

2022-08-29 22:17 UTC, cjpatton requested changes

2022-08-29 22:17 UTC, cjpatton commented on draft-ietf-ppm-dap.md
> +_robustness_ security goals described in {{!VDAF, Section 9}}.
Sadly I don't think italics get rendered in txt the way you want https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap
```suggestion
In the presence of this adversary, DAP aims to achieve the "privacy" and
"robustness" security goals described in {{!VDAF, Section 9}}.
```

2022-08-30 00:08 UTC, cjpatton approved these changes

2022-08-30 00:08 UTC, cjpatton commented on draft-ietf-ppm-dap.md
> +robustness security goals described in {{!VDAF, Section 9}}.
The section number is subject to change (if, for example, we add a new VDAF). Maybe refer to security considerations, just to make our lives later in the future.

2022-09-06 16:23 UTC, cjpatton commented
@tgeoghegan let's squash-then-merge this change.

2022-09-06 16:51 UTC, merged