Use structs for AAD encoding
ietf-wg-ppm/draft-ietf-ppm-dap pull request #372
Opened 2022-10-31 22:32 UTC by divergentdave

This revises the sections dealing with encryption and decryption of input shares and aggregate shares, rewriting the construction of each AAD input to be in terms of RFC 8446-style structs instead of byte string concatenation. This fixes #371.

2022-11-02 00:27 UTC, cjpatton approved these changes
Solid implementation, and a clear win 👍

2022-11-02 15:23 UTC, tgeoghegan approved these changes

2022-11-02 16:01 UTC, ekr requested changes
Generally LGTM.

2022-11-02 16:01 UTC, ekr commented on draft-ietf-ppm-dap.md
> +of the `AggregateShareReq`, with the following format:
```suggestion
`server_role` is `0x02` for the leader and `0x03` for a helper, and
`agg_share_aad` is a value of type `AggregateShareAAD` with its values set from the corresponding fields of the `AggregateShareReq`.
```

2022-11-02 16:01 UTC, ekr commented on draft-ietf-ppm-dap.md
> +response to its query:
```suggestion
response to its query as follows:
```

2022-11-03 20:39 UTC, wangshan commented on draft-ietf-ppm-dap.md
> +} InputShareAAD;
nit: if we follow he same camel case convention of types, this should be `InputShareAad`. Same applies to `AggregateShareAad`

2022-11-03 22:13 UTC, wangshan approved these changes

2022-11-08 23:30 UTC, divergentdave commented
I squashed this back into two commits and then rebased to fix some conflicts.

2022-11-08 23:37 UTC, cjpatton commented
@ekr would you mind taking a quick look?

2022-11-09 13:43 UTC, ekr approved these changes
LGTM

2022-11-09 16:23 UTC, merged