Rewrite verification key example
ietf-wg-ppm/draft-ietf-ppm-dap pull request #513
Opened 2023-10-19 22:38 UTC by chris-wood

Closes #414

2023-10-19 22:40 UTC, cjpatton approved these changes
🦆 - very nice to have a clear example of this. For the record, this is what we do in https://github.com/wangshan/draft-wang-ppm-dap-taskprov. If and when that gets adopted by the WG, we should add a reference to it here.

2023-10-19 23:17 UTC, tgeoghegan requested changes
I think gesturing at the out of band agreement to a verify key seed is unnecessarily complicated for illustrating this. taskprov requires multiple independent actors to independently derive the same task ID, so you need a previously agreed upon verify key seed. But in the task provisioning protocol we worked out for Divvi Up, we have a single entity responsible for choosing the task ID and then distributing it to participating aggregators, so we just randomly generate the verify key and then take a SHA-256 of that.

2023-10-19 23:50 UTC, chris-wood commented
@tgeoghegan that's fine to include as an example. The point here is to not be prescriptive.

2023-10-23 17:34 UTC, tgeoghegan approved these changes

2023-10-23 20:16 UTC, merged